name: stranger_confide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cyr_flutter_core:
    path: ../../cyr_flutter_core

  # Navigation
  go_router: ^14.6.3

  # State management
  flutter_bloc: ^9.1.1

  # Immutable models & states
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

  # Networking
  dio: ^5.7.0
  retrofit: ^4.9.2
  socket_io_client: ^3.0.2
  chuck_interceptor: ^2.4.0

  # Dependency injection
  get_it: ^9.2.1
  injectable: ^2.5.0

  # UI
  google_fonts: ^6.2.1
  intl: ^0.20.2
  curl_logger_dio_interceptor: ^1.0.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  gap: ^3.0.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.4
  easy_localization: ^3.0.7
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  firebase_core: ^4.12.1
  firebase_messaging: ^16.2.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  retrofit_generator: ^10.2.5
  injectable_generator: ^2.7.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/translations/
