// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABnBhUyIlHu7fH7JfaTg8M5vDfgRrugjg',
    appId: '1:610348462005:web:f779509912290c8c5833fc',
    messagingSenderId: '610348462005',
    projectId: 'stranger-confide',
    authDomain: 'stranger-confide.firebaseapp.com',
    storageBucket: 'stranger-confide.firebasestorage.app',
    measurementId: 'G-XGYRRZY9V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhfKx9TRuwHrPnMM7fUMPZIylTQc7WFhY',
    appId: '1:610348462005:android:12488ec432af04885833fc',
    messagingSenderId: '610348462005',
    projectId: 'stranger-confide',
    storageBucket: 'stranger-confide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9akv-YJM6A64rIO3u1j5mGB44YHvPejI',
    appId: '1:610348462005:ios:64aed1d73460edcb5833fc',
    messagingSenderId: '610348462005',
    projectId: 'stranger-confide',
    storageBucket: 'stranger-confide.firebasestorage.app',
    iosBundleId: 'com.cyr.talkfirst',
  );
}
